package persistence.entity.event;

import org.bson.types.ObjectId;
import persistence.entity.Entity;

import java.util.Date;
import java.util.Objects;

public class Event implements Entity<Event> {

	private ObjectId id;
	private String name;

	private String address;
	private String description;
	private Date startDate;
	private Date endDate;

	private ObjectId company;

	public Event() { }

	public Event(String name, String address, String description, Date startDate, Date endDate, ObjectId company) {
		this.name = name;
		this.address = address;
		this.description = description;
		this.startDate = startDate;
		this.endDate = endDate;
		this.company = company;
	}

	/**
	 * The user should not be able to set the id. It is automatically generated by the database.
	 */
	@Override
	public void handleOnCreate() {
		this.id = null;
	}

	public ObjectId getId() {
		return id;
	}

	public void setId(ObjectId id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() { return description; }
	public Date getStartDate() { return startDate; }

	public Date getEndDate() { return endDate; }

	public void setDescription(String description) { this.description = description; }

	public void setStartDate(Date startDate) { this.startDate = startDate; }

	public void setEndDate(Date endDate) { this.endDate = endDate; }

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public ObjectId getCompany() {
		return company;
	}

	public void setCompany(ObjectId company) {
		this.company = company;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;
		Event event = (Event) o;
		return Objects.equals(id, event.id) && Objects.equals(name, event.name) && Objects.equals(address, event.address) && Objects.equals(description, event.description) && Objects.equals(startDate, event.startDate) && Objects.equals(endDate, event.endDate) && Objects.equals(company, event.company);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, name, address, description, startDate, endDate, company);
	}

	@Override
	public int compareTo(Event o) {
		return name.compareTo(o.name);
	}
}
